# Generated by Django 3.2.6 on 2021-08-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210822_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Member',
            new_name='HouseholdMember',
        ),
    ]
