# Generated by Django 3.2.6 on 2021-08-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_household_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmember',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
