# Generated by Django 3.2.6 on 2021-08-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210825_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(blank=True, default='_', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='phone_number',
            field=models.CharField(blank=True, default='_', max_length=10),
            preserve_default=False,
        ),
    ]
