# Generated by Django 3.2.7 on 2021-09-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210825_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
