# Generated by Django 3.2.7 on 2021-10-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_household_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
