# Generated by Django 3.2.7 on 2021-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_householdmember_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
